import { NextRequest, NextResponse } from "next/server";
import { getSession, deleteSession } from "@/lib/session";
import { classifyBreach } from "@/lib/bcBreachRules";
import { renderPdfFromHtml } from "@/lib/documents/renderPdf";

const breachTypeLabels: Record<string, string> = {
  non_payment: "Non-payment of rent",
  unauthorized_occupants: "Unauthorized occupants",
  unauthorized_pets: "Unauthorized pets",
  noise_disturbance: "Noise disturbance",
  property_damage: "Property damage",
  illegal_activity: "Illegal activity",
  other: "Other",
};

function formatDate(dateStr: string): string {
  if (!dateStr) return "";
  const [year, month, day] = dateStr.split("-").map(Number);
  const date = new Date(year, month - 1, day);
  return date.toLocaleDateString("en-CA", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const token = searchParams.get("token");

    if (!token || typeof token !== "string") {
      return NextResponse.json(
        { success: false, error: "Missing token" },
        { status: 400 }
      );
    }

    const data = getSession(token);
    if (!data) {
      return NextResponse.json(
        { success: false, error: "Session not found or expired" },
        { status: 404 }
      );
    }

    const form = data as Record<string, unknown>;

    const landlordName = String(form.landlordName || "");
    const landlordAddressLine1 = String(form.landlordAddressLine1 || "");
    const landlordAddressLine2 = form.landlordAddressLine2
      ? String(form.landlordAddressLine2)
      : "";
    const landlordCity = String(form.landlordCity || "");
    const landlordPostalCode = String(form.landlordPostalCode || "");
    const tenantName = String(form.tenantName || "");
    const rentalAddressLine1 = String(form.rentalAddressLine1 || "");
    const rentalAddressLine2 = form.rentalAddressLine2
      ? String(form.rentalAddressLine2)
      : "";
    const rentalCity = String(form.rentalCity || "");
    const rentalPostalCode = String(form.rentalPostalCode || "");
    const breachType = String(form.breachType || "");
    const breachDescription = String(form.breachDescription || "");
    const dateBreachOccurred = String(form.dateBreachOccurred || "");
    const hasEvidence = Boolean(form.hasEvidence);
    const requiredActionDescription = String(form.requiredActionDescription || "");
    const deadlineToFix = String(form.deadlineToFix || "");

    const { severity, recommendedFixDays } = classifyBreach(breachType);
    const breachLabel = breachTypeLabels[breachType] || breachType;

    const evidenceNote = hasEvidence
      ? `<p>The landlord has evidence available upon request.</p>`
      : "";

    const html = `
<h1>Breach Notice – British Columbia</h1>

<div style="margin-bottom: 16pt;">
  <p><strong>Landlord:</strong> ${escapeHtml(landlordName)}<br>
  ${escapeHtml(landlordAddressLine1)}<br>
  ${landlordAddressLine2 ? escapeHtml(landlordAddressLine2) + "<br>" : ""}
  ${escapeHtml(landlordCity)}, ${escapeHtml(landlordPostalCode)}</p>

  <p><strong>Tenant:</strong> ${escapeHtml(tenantName)}<br>
  ${escapeHtml(rentalAddressLine1)}<br>
  ${rentalAddressLine2 ? escapeHtml(rentalAddressLine2) + "<br>" : ""}
  ${escapeHtml(rentalCity)}, ${escapeHtml(rentalPostalCode)}</p>
</div>

<h2>Breach Details</h2>
<ul>
  <li>Breach type: ${escapeHtml(breachLabel)}</li>
  <li>Description of breach: ${escapeHtml(breachDescription)}</li>
  <li>Date breach occurred: ${formatDate(dateBreachOccurred)}</li>
  <li>Severity classification: ${escapeHtml(severity)}</li>
  <li>Recommended correction timeline: ${recommendedFixDays} days</li>
</ul>

${evidenceNote}

<h2>Required Action</h2>
<p>${escapeHtml(requiredActionDescription)}</p>
<p>Deadline to fix: ${formatDate(deadlineToFix)}</p>

<h2>Legal Reference</h2>
<p>Under the Residential Tenancy Act, tenants must comply with the terms of the tenancy agreement and must not cause unreasonable disturbance or damage.</p>

<h2>Signature</h2>
<p>Landlord: ${escapeHtml(landlordName)}</p>
<p style="margin-top: 24pt;">______________________________<br>Signature</p>
<p style="margin-top: 16pt;">Date: ______________</p>

<div style="margin-top: 40pt; padding-top: 12pt; border-top: 1px solid #cbd5e1; font-size: 10pt; color: #64748b;">
  <p>Generated by LegalCals.com. This is not legal advice.</p>
</div>
`;

    const pdf = await renderPdfFromHtml(html);

    deleteSession(token);

    return new NextResponse(new Uint8Array(pdf), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="bc-breach-notice.pdf"`,
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return NextResponse.json(
      { success: false, error: message },
      { status: 500 }
    );
  }
}
