import { NextRequest, NextResponse } from "next/server";
import { getSession, deleteSession } from "@/lib/session";
import { renderPdfFromHtml } from "@/lib/documents/renderPdf";

function formatDate(dateStr: string): string {
  if (!dateStr) return "";
  const [year, month, day] = dateStr.split("-").map(Number);
  const date = new Date(year, month - 1, day);
  return date.toLocaleDateString("en-CA", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const token = searchParams.get("token");

    if (!token || typeof token !== "string") {
      return NextResponse.json(
        { success: false, error: "Missing token" },
        { status: 400 }
      );
    }

    const data = getSession(token);
    if (!data) {
      return NextResponse.json(
        { success: false, error: "Session not found or expired" },
        { status: 404 }
      );
    }

    const form = data as Record<string, unknown>;

    const landlordName = String(form.landlordName || "");
    const landlordAddress = String(form.landlordAddress || "");
    const tenantName = String(form.tenantName || "");
    const rentalAddress = String(form.rentalAddress || "");
    const rentAmountOwing = Number(form.rentAmountOwing || 0);
    const rentPeriod = String(form.rentPeriod || "");
    const noticeDate = String(form.noticeDate || "");
    const evictionDate = String(form.evictionDate || "");
    const additionalNotes = form.additionalNotes
      ? String(form.additionalNotes)
      : "";

    if (
      !landlordName ||
      !landlordAddress ||
      !tenantName ||
      !rentalAddress ||
      !rentPeriod ||
      !noticeDate ||
      !evictionDate
    ) {
      return NextResponse.json(
        { success: false, error: "Missing required fields" },
        { status: 400 }
      );
    }

    const additionalNotesDisplay = additionalNotes
      ? escapeHtml(additionalNotes)
      : "None provided.";

    const html = `
<h1>14‑Day Eviction Notice for Non‑Payment of Rent — Alberta</h1>

<div style="margin-bottom: 16pt;">
  <p><strong>Landlord:</strong><br>
  ${escapeHtml(landlordName)}<br>
  ${escapeHtml(landlordAddress)}</p>

  <p><strong>Tenant:</strong><br>
  ${escapeHtml(tenantName)}<br>
  ${escapeHtml(rentalAddress)}</p>
</div>

<p><strong>Rent Owing:</strong> $${rentAmountOwing.toFixed(2)}</p>
<p><strong>Rent Period:</strong> ${escapeHtml(rentPeriod)}</p>
<p><strong>Notice Date:</strong> ${formatDate(noticeDate)}</p>
<p><strong>Eviction Date (14 days after notice):</strong> ${formatDate(evictionDate)}</p>

<h2>Statement</h2>
<p>This notice is issued because rent has not been paid for the period listed above. Under the Alberta Residential Tenancies Act, a landlord may terminate a tenancy with 14 days' written notice when a tenant fails to pay rent on time. The tenant must vacate the rental premises by the eviction date stated in this notice unless the landlord agrees in writing to withdraw or amend this notice.</p>

<h2>Additional Notes</h2>
<p>${additionalNotesDisplay}</p>

<h2>Signature</h2>
<p>Landlord</p>
<p style="margin-top: 24pt;">______________________________<br>Signature</p>
<p style="margin-top: 16pt;">Date: ______________</p>

<div style="margin-top: 40pt; padding-top: 12pt; border-top: 1px solid #cbd5e1; font-size: 10pt; color: #64748b;">
  <p>Generated by LegalCals.com. This is not legal advice.</p>
</div>
`;

    const pdf = await renderPdfFromHtml(html);

    deleteSession(token);

    return new NextResponse(new Uint8Array(pdf), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="ab-eviction-14-day.pdf"`,
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return NextResponse.json(
      { success: false, error: message },
      { status: 500 }
    );
  }
}
