import { NextRequest, NextResponse } from "next/server";
import { getSession, deleteSession } from "@/lib/session";
import { validateMutualAgreement } from "@/lib/bcMutualEndRules";
import { renderPdfFromHtml } from "@/lib/documents/renderPdf";

function formatDate(dateStr: string): string {
  if (!dateStr) return "";
  const [year, month, day] = dateStr.split("-").map(Number);
  const date = new Date(year, month - 1, day);
  return date.toLocaleDateString("en-CA", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const token = searchParams.get("token");

    if (!token || typeof token !== "string") {
      return NextResponse.json(
        { success: false, error: "Missing token" },
        { status: 400 }
      );
    }

    const data = getSession(token);
    if (!data) {
      return NextResponse.json(
        { success: false, error: "Session not found or expired" },
        { status: 404 }
      );
    }

    const form = data as Record<string, unknown>;

    const tenancyStartDate = String(form.tenancyStartDate || "");
    const agreedMoveOutDate = String(form.agreedMoveOutDate || "");

    const { valid } = validateMutualAgreement(tenancyStartDate, agreedMoveOutDate);
    if (!valid) {
      return NextResponse.json(
        { success: false, error: "Agreement date validation failed" },
        { status: 400 }
      );
    }

    const landlordName = String(form.landlordName || "");
    const landlordAddressLine1 = String(form.landlordAddressLine1 || "");
    const landlordAddressLine2 = form.landlordAddressLine2
      ? String(form.landlordAddressLine2)
      : "";
    const landlordCity = String(form.landlordCity || "");
    const landlordPostalCode = String(form.landlordPostalCode || "");
    const tenantName = String(form.tenantName || "");
    const rentalAddressLine1 = String(form.rentalAddressLine1 || "");
    const rentalAddressLine2 = form.rentalAddressLine2
      ? String(form.rentalAddressLine2)
      : "";
    const rentalCity = String(form.rentalCity || "");
    const rentalPostalCode = String(form.rentalPostalCode || "");
    const tenantWillVacateByTime = String(form.tenantWillVacateByTime || "");
    const landlordWillForgiveRentArrears = Boolean(
      form.landlordWillForgiveRentArrears
    );
    const landlordWillReturnDepositInFull = Boolean(
      form.landlordWillReturnDepositInFull
    );
    const additionalTerms = form.additionalTerms
      ? String(form.additionalTerms)
      : "";

    let agreementDetailsHtml = "";
    if (landlordWillForgiveRentArrears) {
      agreementDetailsHtml += `<p>The landlord agrees to forgive any outstanding rent arrears.</p>`;
    }
    if (landlordWillReturnDepositInFull) {
      agreementDetailsHtml += `<p>The landlord agrees to return the full security deposit.</p>`;
    }
    if (additionalTerms) {
      agreementDetailsHtml += `<p>Additional terms: ${escapeHtml(additionalTerms)}</p>`;
    }

    const html = `
<h1>Mutual Agreement to End Tenancy – British Columbia</h1>

<div style="margin-bottom: 16pt;">
  <p><strong>Landlord:</strong> ${escapeHtml(landlordName)}<br>
  ${escapeHtml(landlordAddressLine1)}<br>
  ${landlordAddressLine2 ? escapeHtml(landlordAddressLine2) + "<br>" : ""}
  ${escapeHtml(landlordCity)}, ${escapeHtml(landlordPostalCode)}</p>

  <p><strong>Tenant:</strong> ${escapeHtml(tenantName)}<br>
  ${escapeHtml(rentalAddressLine1)}<br>
  ${rentalAddressLine2 ? escapeHtml(rentalAddressLine2) + "<br>" : ""}
  ${escapeHtml(rentalCity)}, ${escapeHtml(rentalPostalCode)}</p>
</div>

<h2>Agreement Details</h2>
<ul>
  <li>Tenancy start date: ${formatDate(tenancyStartDate)}</li>
  <li>Agreed move-out date: ${formatDate(agreedMoveOutDate)}</li>
  <li>Tenant will vacate by: ${escapeHtml(tenantWillVacateByTime)}</li>
</ul>

${agreementDetailsHtml}

<h2>Legal Reference</h2>
<p>This agreement is made voluntarily by both parties under the Residential Tenancy Act.</p>

<h2>Signatures</h2>

<div style="margin-bottom: 24pt;">
  <p><strong>Landlord:</strong> ${escapeHtml(landlordName)}</p>
  <p style="margin-top: 16pt;">______________________________<br>Signature</p>
  <p style="margin-top: 8pt;">Date: ______________</p>
</div>

<div>
  <p><strong>Tenant:</strong> ${escapeHtml(tenantName)}</p>
  <p style="margin-top: 16pt;">______________________________<br>Signature</p>
  <p style="margin-top: 8pt;">Date: ______________</p>
</div>

<div style="margin-top: 40pt; padding-top: 12pt; border-top: 1px solid #cbd5e1; font-size: 10pt; color: #64748b;">
  <p>Generated by LegalCals.com. This is not legal advice.</p>
</div>
`;

    const pdf = await renderPdfFromHtml(html);

    deleteSession(token);

    return new NextResponse(new Uint8Array(pdf), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="bc-mutual-agreement-to-end-tenancy.pdf"`,
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return NextResponse.json(
      { success: false, error: message },
      { status: 500 }
    );
  }
}
