export const usStates = {
  al: { name: "Alabama", slug: "al", accent: "#9E1B32", seal: "/seals/us/al.png" },
  ak: { name: "Alaska", slug: "ak", accent: "#0F204B", seal: "/seals/us/ak.png" },
  az: { name: "Arizona", slug: "az", accent: "#BF0A30", seal: "/seals/us/az.png" },
  ar: { name: "Arkansas", slug: "ar", accent: "#9D2235", seal: "/seals/us/ar.png" },
  ca: { name: "California", slug: "ca", accent: "#FCB813", seal: "/seals/us/ca.png" },
  co: { name: "Colorado", slug: "co", accent: "#003366", seal: "/seals/us/co.png" },
  ct: { name: "Connecticut", slug: "ct", accent: "#0033A0", seal: "/seals/us/ct.png" },
  de: { name: "Delaware", slug: "de", accent: "#0074AD", seal: "/seals/us/de.png" },
  fl: { name: "Florida", slug: "fl", accent: "#F36F21", seal: "/seals/us/fl.png" },
  ga: { name: "Georgia", slug: "ga", accent: "#B5002D", seal: "/seals/us/ga.png" },
  hi: { name: "Hawaii", slug: "hi", accent: "#C8102E", seal: "/seals/us/hi.png" },
  id: { name: "Idaho", slug: "id", accent: "#003E7E", seal: "/seals/us/id.png" },
  il: { name: "Illinois", slug: "il", accent: "#002855", seal: "/seals/us/il.png" },
  in: { name: "Indiana", slug: "in", accent: "#002D72", seal: "/seals/us/in.png" },
  ia: { name: "Iowa", slug: "ia", accent: "#C8102E", seal: "/seals/us/ia.png" },
  ks: { name: "Kansas", slug: "ks", accent: "#0033A0", seal: "/seals/us/ks.png" },
  ky: { name: "Kentucky", slug: "ky", accent: "#0033A0", seal: "/seals/us/ky.png" },
  la: { name: "Louisiana", slug: "la", accent: "#0A3161", seal: "/seals/us/la.png" },
  me: { name: "Maine", slug: "me", accent: "#003C71", seal: "/seals/us/me.png" },
  md: { name: "Maryland", slug: "md", accent: "#000000", seal: "/seals/us/md.png" },
  ma: { name: "Massachusetts", slug: "ma", accent: "#002D72", seal: "/seals/us/ma.png" },
  mi: { name: "Michigan", slug: "mi", accent: "#00274C", seal: "/seals/us/mi.png" },
  mn: { name: "Minnesota", slug: "mn", accent: "#003DA5", seal: "/seals/us/mn.png" },
  ms: { name: "Mississippi", slug: "ms", accent: "#C8102E", seal: "/seals/us/ms.png" },
  mo: { name: "Missouri", slug: "mo", accent: "#002F6C", seal: "/seals/us/mo.png" },
  mt: { name: "Montana", slug: "mt", accent: "#002F6C", seal: "/seals/us/mt.png" },
  ne: { name: "Nebraska", slug: "ne", accent: "#E41C38", seal: "/seals/us/ne.png" },
  nv: { name: "Nevada", slug: "nv", accent: "#003366", seal: "/seals/us/nv.png" },
  nh: { name: "New Hampshire", slug: "nh", accent: "#0033A0", seal: "/seals/us/nh.png" },
  nj: { name: "New Jersey", slug: "nj", accent: "#002D72", seal: "/seals/us/nj.png" },
  nm: { name: "New Mexico", slug: "nm", accent: "#FFD700", seal: "/seals/us/nm.png" },
  ny: { name: "New York", slug: "ny", accent: "#0033A0", seal: "/seals/us/ny.png" },
  nc: { name: "North Carolina", slug: "nc", accent: "#0033A0", seal: "/seals/us/nc.png" },
  nd: { name: "North Dakota", slug: "nd", accent: "#0033A0", seal: "/seals/us/nd.png" },
  oh: { name: "Ohio", slug: "oh", accent: "#C8102E", seal: "/seals/us/oh.png" },
  ok: { name: "Oklahoma", slug: "ok", accent: "#0072CE", seal: "/seals/us/ok.png" },
  or: { name: "Oregon", slug: "or", accent: "#154734", seal: "/seals/us/or.png" },
  pa: { name: "Pennsylvania", slug: "pa", accent: "#0033A0", seal: "/seals/us/pa.png" },
  ri: { name: "Rhode Island", slug: "ri", accent: "#0033A0", seal: "/seals/us/ri.png" },
  sc: { name: "South Carolina", slug: "sc", accent: "#003366", seal: "/seals/us/sc.png" },
  sd: { name: "South Dakota", slug: "sd", accent: "#00A3E0", seal: "/seals/us/sd.png" },
  tn: { name: "Tennessee", slug: "tn", accent: "#CC0000", seal: "/seals/us/tn.png" },
  tx: { name: "Texas", slug: "tx", accent: "#BF0A30", seal: "/seals/us/tx.png" },
  ut: { name: "Utah", slug: "ut", accent: "#002868", seal: "/seals/us/ut.png" },
  vt: { name: "Vermont", slug: "vt", accent: "#005A2B", seal: "/seals/us/vt.png" },
  va: { name: "Virginia", slug: "va", accent: "#002D72", seal: "/seals/us/va.png" },
  wa: { name: "Washington", slug: "wa", accent: "#006C54", seal: "/seals/us/wa.png" },
  wv: { name: "West Virginia", slug: "wv", accent: "#0033A0", seal: "/seals/us/wv.png" },
  wi: { name: "Wisconsin", slug: "wi", accent: "#0033A0", seal: "/seals/us/wi.png" },
  wy: { name: "Wyoming", slug: "wy", accent: "#FFC72C", seal: "/seals/us/wy.png" }
};