import { NextRequest, NextResponse } from "next/server";
import { getSession, deleteSession } from "@/lib/session";
import { renderPdfFromHtml } from "@/lib/documents/renderPdf";

function formatDate(dateStr: string): string {
  if (!dateStr) return "";
  const [year, month, day] = dateStr.split("-").map(Number);
  const date = new Date(year, month - 1, day);
  return date.toLocaleDateString("en-CA", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const token = searchParams.get("token");

    if (!token || typeof token !== "string") {
      return NextResponse.json(
        { success: false, error: "Missing token" },
        { status: 400 }
      );
    }

    const data = getSession(token);
    if (!data) {
      return NextResponse.json(
        { success: false, error: "Session not found or expired" },
        { status: 404 }
      );
    }

    const form = data as Record<string, unknown>;

    const landlordName = String(form.landlordName || "");
    const landlordAddress = String(form.landlordAddress || "");
    const tenantName = String(form.tenantName || "");
    const rentalAddress = String(form.rentalAddress || "");
    const entryDate = String(form.entryDate || "");
    const entryTime = String(form.entryTime || "");
    const entryReason = String(form.entryReason || "");
    const additionalNotes = form.additionalNotes
      ? String(form.additionalNotes)
      : "";

    if (
      !landlordName ||
      !landlordAddress ||
      !tenantName ||
      !rentalAddress ||
      !entryDate ||
      !entryTime ||
      !entryReason
    ) {
      return NextResponse.json(
        { success: false, error: "Missing required fields" },
        { status: 400 }
      );
    }

    const additionalNotesDisplay = additionalNotes
      ? escapeHtml(additionalNotes)
      : "None provided.";

    const html = `
<h1>Notice to Enter Rental Premises — Alberta</h1>

<div style="margin-bottom: 16pt;">
  <p><strong>Landlord:</strong><br>
  ${escapeHtml(landlordName)}<br>
  ${escapeHtml(landlordAddress)}</p>

  <p><strong>Tenant:</strong><br>
  ${escapeHtml(tenantName)}<br>
  ${escapeHtml(rentalAddress)}</p>
</div>

<p><strong>Entry Date:</strong> ${formatDate(entryDate)}</p>
<p><strong>Entry Time:</strong> ${escapeHtml(entryTime)}</p>
<p><strong>Reason for Entry:</strong> ${escapeHtml(entryReason)}</p>

<h2>Statement</h2>
<p>This notice is provided under the Alberta Residential Tenancies Act. The landlord intends to enter the rental premises on the date and time stated above for the purpose described. Except in emergencies or with the tenant's consent, landlords must provide proper written notice before entering a rental unit.</p>

<h2>Additional Notes</h2>
<p>${additionalNotesDisplay}</p>

<h2>Signature</h2>
<p>Landlord</p>
<p style="margin-top: 24pt;">______________________________<br>Signature</p>
<p style="margin-top: 16pt;">Date: ______________</p>

<div style="margin-top: 40pt; padding-top: 12pt; border-top: 1px solid #cbd5e1; font-size: 10pt; color: #64748b;">
  <p>Generated by LegalCals.com. This is not legal advice.</p>
</div>
`;

    const pdf = await renderPdfFromHtml(html);

    deleteSession(token);

    return new NextResponse(new Uint8Array(pdf), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="ab-notice-to-enter.pdf"`,
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return NextResponse.json(
      { success: false, error: message },
      { status: 500 }
    );
  }
}
