import { NextRequest, NextResponse } from "next/server";
import { getSession, deleteSession } from "@/lib/session";
import { renderPdfFromHtml } from "@/lib/documents/renderPdf";

function formatDate(dateStr: string): string {
  if (!dateStr) return "";
  const [year, month, day] = dateStr.split("-").map(Number);
  const date = new Date(year, month - 1, day);
  return date.toLocaleDateString("en-CA", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const token = searchParams.get("token");

    if (!token || typeof token !== "string") {
      return NextResponse.json(
        { success: false, error: "Missing token" },
        { status: 400 }
      );
    }

    const data = getSession(token);
    if (!data) {
      return NextResponse.json(
        { success: false, error: "Session not found or expired" },
        { status: 404 }
      );
    }

    const form = data as Record<string, unknown>;

    const landlordName = String(form.landlordName || "");
    const landlordAddress = String(form.landlordAddress || "");
    const tenantName = String(form.tenantName || "");
    const rentalAddress = String(form.rentalAddress || "");
    const depositAmount = Number(form.depositAmount || 0);
    const moveOutDate = String(form.moveOutDate || "");
    const amountReturned = Number(form.amountReturned || 0);
    const amountWithheld = Number(form.amountWithheld || 0);
    const withholdingReason = form.withholdingReason
      ? String(form.withholdingReason)
      : "";
    const additionalNotes = form.additionalNotes
      ? String(form.additionalNotes)
      : "";

    if (
      !landlordName ||
      !landlordAddress ||
      !tenantName ||
      !rentalAddress ||
      !moveOutDate
    ) {
      return NextResponse.json(
        { success: false, error: "Missing required fields" },
        { status: 400 }
      );
    }

    const withholdingReasonDisplay = withholdingReason
      ? escapeHtml(withholdingReason)
      : "None provided.";
    const additionalNotesDisplay = additionalNotes
      ? escapeHtml(additionalNotes)
      : "None provided.";

    const html = `
<h1>Security Deposit Return Statement — Alberta</h1>

<div style="margin-bottom: 16pt;">
  <p><strong>Landlord:</strong><br>
  ${escapeHtml(landlordName)}<br>
  ${escapeHtml(landlordAddress)}</p>

  <p><strong>Tenant:</strong><br>
  ${escapeHtml(tenantName)}<br>
  ${escapeHtml(rentalAddress)}</p>
</div>

<p><strong>Original Deposit Amount:</strong> $${depositAmount.toFixed(2)}</p>
<p><strong>Move‑Out Date:</strong> ${formatDate(moveOutDate)}</p>
<p><strong>Amount Returned:</strong> $${amountReturned.toFixed(2)}</p>
<p><strong>Amount Withheld:</strong> $${amountWithheld.toFixed(2)}</p>

<h2>Reason for Withholding</h2>
<p>${withholdingReasonDisplay}</p>

<h2>Statement</h2>
<p>This statement is provided under the Alberta Residential Tenancies Act. Landlords must return the security deposit, minus any lawful deductions, within the required timeline after the tenant moves out. Any withheld amount must be supported by a written explanation.</p>

<h2>Additional Notes</h2>
<p>${additionalNotesDisplay}</p>

<h2>Signature</h2>
<p>Landlord</p>
<p style="margin-top: 24pt;">______________________________<br>Signature</p>
<p style="margin-top: 16pt;">Date: ______________</p>

<div style="margin-top: 40pt; padding-top: 12pt; border-top: 1px solid #cbd5e1; font-size: 10pt; color: #64748b;">
  <p>Generated by LegalCals.com. This is not legal advice.</p>
</div>
`;

    const pdf = await renderPdfFromHtml(html);

    deleteSession(token);

    return new NextResponse(new Uint8Array(pdf), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="ab-security-deposit-return.pdf"`,
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return NextResponse.json(
      { success: false, error: message },
      { status: 500 }
    );
  }
}
