export interface Jurisdiction {
  country: string;
  code: string;
  name: string;
  type: "state" | "province" | "territory" | "district";
  calculators: string[];
  documents?: string[];
}

export const jurisdictions: Jurisdiction[] = [
  {
    country: "ca",
    code: "bc",
    name: "British Columbia",
    type: "province" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "ca",
    code: "ab",
    name: "Alberta",
    type: "province" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "ca",
    code: "sk",
    name: "Saskatchewan",
    type: "province" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "ca",
    code: "mb",
    name: "Manitoba",
    type: "province" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "ca",
    code: "on",
    name: "Ontario",
    type: "province" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "ca",
    code: "qc",
    name: "Quebec",
    type: "province" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "ca",
    code: "nb",
    name: "New Brunswick",
    type: "province" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "ca",
    code: "ns",
    name: "Nova Scotia",
    type: "province" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "ca",
    code: "pe",
    name: "Prince Edward Island",
    type: "province" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "ca",
    code: "nl",
    name: "Newfoundland and Labrador",
    type: "province" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "ca",
    code: "yt",
    name: "Yukon",
    type: "territory" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "ca",
    code: "nt",
    name: "Northwest Territories",
    type: "territory" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "ca",
    code: "nu",
    name: "Nunavut",
    type: "territory" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "al",
    name: "Alabama",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "ak",
    name: "Alaska",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "az",
    name: "Arizona",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "ar",
    name: "Arkansas",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "ca",
    name: "California",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "co",
    name: "Colorado",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "ct",
    name: "Connecticut",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "de",
    name: "Delaware",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "fl",
    name: "Florida",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "ga",
    name: "Georgia",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "hi",
    name: "Hawaii",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "id",
    name: "Idaho",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "il",
    name: "Illinois",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "in",
    name: "Indiana",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "ia",
    name: "Iowa",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "ks",
    name: "Kansas",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "ky",
    name: "Kentucky",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "la",
    name: "Louisiana",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "me",
    name: "Maine",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "md",
    name: "Maryland",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "ma",
    name: "Massachusetts",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "mi",
    name: "Michigan",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "mn",
    name: "Minnesota",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "ms",
    name: "Mississippi",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "mo",
    name: "Missouri",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "mt",
    name: "Montana",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "ne",
    name: "Nebraska",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "nv",
    name: "Nevada",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "nh",
    name: "New Hampshire",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "nj",
    name: "New Jersey",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "nm",
    name: "New Mexico",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "ny",
    name: "New York",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "nc",
    name: "North Carolina",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "nd",
    name: "North Dakota",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "oh",
    name: "Ohio",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "ok",
    name: "Oklahoma",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "or",
    name: "Oregon",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "pa",
    name: "Pennsylvania",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "ri",
    name: "Rhode Island",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "sc",
    name: "South Carolina",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "sd",
    name: "South Dakota",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "tn",
    name: "Tennessee",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "tx",
    name: "Texas",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "ut",
    name: "Utah",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "vt",
    name: "Vermont",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "va",
    name: "Virginia",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "wa",
    name: "Washington",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "wv",
    name: "West Virginia",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "wi",
    name: "Wisconsin",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "wy",
    name: "Wyoming",
    type: "state" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
  {
    country: "us",
    code: "dc",
    name: "District of Columbia",
    type: "district" as const,
    calculators: ["condition-inspection", "deposit-return", "duplicate-receipt", "ending-tenancy", "entry-notice", "eviction-timeline", "late-fee", "late-status", "lease-termination", "ledger-validation", "payment-methods", "payment-proof", "receipt-validation", "rent-increase", "rent-receipt", "repair-deduct", "repair-request", "security-deposit", "withhold-rent"],
  },
];

export function getJurisdiction(country: string, code: string): Jurisdiction | undefined {
  return jurisdictions.find(
    (j) => j.country.toLowerCase() === country.toLowerCase() && j.code.toLowerCase() === code.toLowerCase()
  );
}

export function listJurisdictionsByCountry(country: string): Jurisdiction[] {
  return jurisdictions.filter(
    (j) => j.country.toLowerCase() === country.toLowerCase()
  );
}
