import { NextRequest, NextResponse } from "next/server";
import { getSession, deleteSession } from "@/lib/session";
import { validateArrears } from "@/lib/bcRentArrearsRules";
import { renderPdfFromHtml } from "@/lib/documents/renderPdf";

function formatCurrency(value: number): string {
  return new Intl.NumberFormat("en-CA", {
    style: "currency",
    currency: "CAD",
  }).format(value);
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const token = searchParams.get("token");

    if (!token || typeof token !== "string") {
      return NextResponse.json(
        { success: false, error: "Missing token" },
        { status: 400 }
      );
    }

    const data = getSession(token);
    if (!data) {
      return NextResponse.json(
        { success: false, error: "Session not found or expired" },
        { status: 404 }
      );
    }

    const form = data as Record<string, unknown>;

    const monthsOwedRaw = Array.isArray(form.monthsOwed)
      ? (form.monthsOwed as Record<string, unknown>[])
      : [];
    const monthsOwed = monthsOwedRaw.map((m) => ({
      monthLabel: String(m.monthLabel || ""),
      amountOwed: Number(m.amountOwed || 0),
    }));
    const totalArrears = Number(form.totalArrears || 0);

    const { valid } = validateArrears(monthsOwed, totalArrears);
    if (!valid) {
      return NextResponse.json(
        { success: false, error: "Arrears validation failed" },
        { status: 400 }
      );
    }

    const landlordName = String(form.landlordName || "");
    const landlordEmail = form.landlordEmail
      ? String(form.landlordEmail)
      : "";
    const landlordPhone = form.landlordPhone
      ? String(form.landlordPhone)
      : "";
    const tenantName = String(form.tenantName || "");
    const rentalAddressLine1 = String(form.rentalAddressLine1 || "");
    const rentalAddressLine2 = form.rentalAddressLine2
      ? String(form.rentalAddressLine2)
      : "";
    const rentalCity = String(form.rentalCity || "");
    const rentalPostalCode = String(form.rentalPostalCode || "");
    const monthlyRentAmount = Number(form.monthlyRentAmount || 0);
    const additionalNotes = form.additionalNotes
      ? String(form.additionalNotes)
      : "";

    const monthsOwedHtml = monthsOwed
      .map(
        (m) =>
          `<li>${escapeHtml(m.monthLabel)}: ${formatCurrency(m.amountOwed)}</li>`
      )
      .join("\n");

    const additionalNotesHtml = additionalNotes
      ? `<h2>Additional Notes</h2><p>Notes: ${escapeHtml(additionalNotes)}</p>`
      : "";

    const html = `
<h1>Rent Arrears Statement – British Columbia</h1>

<div style="margin-bottom: 16pt;">
  <p><strong>Landlord:</strong> ${escapeHtml(landlordName)}<br>
  ${landlordEmail ? escapeHtml(landlordEmail) + "<br>" : ""}
  ${landlordPhone ? escapeHtml(landlordPhone) + "<br>" : ""}</p>

  <p><strong>Tenant:</strong> ${escapeHtml(tenantName)}<br>
  ${escapeHtml(rentalAddressLine1)}<br>
  ${rentalAddressLine2 ? escapeHtml(rentalAddressLine2) + "<br>" : ""}
  ${escapeHtml(rentalCity)}, ${escapeHtml(rentalPostalCode)}</p>
</div>

<h2>Arrears Summary</h2>
<ul>
  <li>Monthly rent amount: ${formatCurrency(monthlyRentAmount)}</li>
  <li>Total arrears amount: ${formatCurrency(totalArrears)}</li>
</ul>

<h2>Breakdown of Months Owed</h2>
<ul>
${monthsOwedHtml}
</ul>

<h2>Statement</h2>
<p>This statement summarizes the rent arrears owed by the tenant as of the date of issuance.</p>

${additionalNotesHtml}

<h2>Signature</h2>
<p>Landlord: ${escapeHtml(landlordName)}</p>
<p style="margin-top: 24pt;">______________________________<br>Signature</p>
<p style="margin-top: 16pt;">Date: ______________</p>

<div style="margin-top: 40pt; padding-top: 12pt; border-top: 1px solid #cbd5e1; font-size: 10pt; color: #64748b;">
  <p>Generated by LegalCals.com. This is not legal advice.</p>
</div>
`;

    const pdf = await renderPdfFromHtml(html);

    deleteSession(token);

    return new NextResponse(new Uint8Array(pdf), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="bc-rent-arrears-statement.pdf"`,
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return NextResponse.json(
      { success: false, error: message },
      { status: 500 }
    );
  }
}
